import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Calculate from './calculate';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mean, Median , Mode Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}> 
        <Calculate/>
      </main>
    </div>
  )
}
